version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-eventbridge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p8ifvzrnay7x"
s3_prefix = "sam-app-eventbridge"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
