version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tpnt-transmitter"
s3_prefix = "tpnt-transmitter"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
