AWSTemplateFormatVersion: 2010-09-09
Description: Form an aggregator of AWS Config in an individual account

Parameters:
  SourceAccounts:
    Description: Source Accounts where compliance status aggregate from
    Type: CommaDelimitedList
    #https://aws.amazon.com/premiumsupport/knowledge-center/multiple-values-list-parameter-cli/
    #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-securitygroupids
    Default: 111111111111,222222222222

Resources:
  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-config-configurationaggregator-accountaggregationsource.html
  Aggregator:
    Type: AWS::Config::ConfigurationAggregator
    Properties:
      AccountAggregationSources:
        - AccountIds: !Ref SourceAccounts
          AllAwsRegions: True
      ConfigurationAggregatorName: ConfigurationAggregator
