version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "configservice-aggregated-violation-transmitter"
s3_prefix = "configservice-aggregated-violation-transmitter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
