AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cavt

  Sample SAM Template for cavt

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function
      Handler: cavt/app.lambda_handler
      Runtime: python3.8
      Events:
        ScheduledEvent:
          Type: Schedule #https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#example-schedule-event-source-object
          Properties:
            Schedule: rate(6 hours) #https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#RateExpressions
            #Schedule: rate(5 minutes)
            Name: my-schedule
            Description: Example schedule
            Enabled: True

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Function:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn
  FunctionIamRole:
    Description: "Implicit IAM Role created for the function"
    Value: !GetAtt FunctionRole.Arn
