version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TagPoliciesNoncomplianceTransmitter"
s3_prefix = "TagPoliciesNoncomplianceTransmitter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Bucket=\"Default\""
